= Общие сведения о модуле {rd}

Конструктор отчётов является дополнительным модулем {dv} и предназначен для формирования отчётов в интерфейсе {wc}а {dv}.

Модуль позволяет формировать отчёты с использованием различных настроек в интерфейсе системы. {rd} поддерживает работу через {wc} в части настройки и пользовательского функционала.
За генерацию отчёта, отвечает Провайдер -- это программный модуль DV, принимающий на вход шаблон отчёта в формате `FastReport` и данные, результатом работы провайдера, является файл отчёта. Настройка формата отчёта выполняется в среде разработки отчётов `FastReport`, в {dv} загружается шаблон отчёта. Архитектура модуля позволяет добавлять дополнительные провайдеры генерации отчётов. Например, если в компании принято использовать Microsoft BI для получения статистических отчётов, то модуль позволит создать такой провайдер, см. раздел "xref:new-provider.adoc[Создание нового Провайдера]".

[#module-structure]
== Структура модуля

Модуль состоит из:

* Расширения сервера {wc}а
* Расширения серверной части
* Расширения клиентской части {wc}а,
* Расширения программы {kvr} и справочников для работы с отчётами
* Справочников, реализованных на базе Конструктора справочников:
** отчёты
** Параметры
** Пользовательские шаблоны параметров отчётов
** Подключения

[#module-functions]
== Назначение и функции модуля

Модуль позволяет создавать новые отчёты, редактировать уже созданные, формировать созданные отчёты при помощи провайдера `FastReport`.

{rd} добавляет новый узел в Конструкторе справочников -- "Конструктор отчётов". Узел содержит следующие справочники:

* отчёты – содержит все имеющиеся отчёты в системе.
* Параметры – содержит все доступные для использования элементы управления для тонкой настройки формы ввода параметров отчёта.
* Пользовательские шаблоны параметров отчётов – содержит предзаполненные параметры по определенному отчёту.
* Провайдеры – содержит все доступные для использования провайдеры для отоб-ражения отчёта с их описанием.
* Подключения – содержит строки подключения для настройки источников дан-ных, используемых в отчётах.

