= Работа с API модуля {rd}

Запросы должны выполняться от авторизованного пользователя {dv}. Для авторизации через API необходимо отправить POST запрос по адресу:

 \https:<.>адрес-{wc}а/Account/Login

.Тело запроса:
[source]
----
{
  UserName,
  Password
}
----

[#GetReportParameters]
== Получение списка доступных параметров отчёта

 /api/Report/GetReportParameters

Для получения списка доступных параметров отчёта применяется GET-запрос с параметрами:

* `reportRowId` -- обязательный параметр, ID строки отчёта в справочнике или название отчёта.

.Возвращает объект:
[source]
----
{
    "code": number, <.>
    "parameters": <.>
        {
            "type": number, <.>
            "value": string, <.>
            "name": string, <.>
            "labelText": string, <.>
            "placeholder": string, <.>
            "itemType": string, <.>
            "properties": string, <.>
            "required": boolean, <.>
            "hidden": boolean <.>
        }[],
    "asyncGenerate": boolean, <.>
    "answer": string, <.>
}
----
<.> Код результата
<.> Массив параметров
<.> Тип параметра
<.> Название ЭУ параметра в программе {kvr}
<.> Название параметра
<.> Локализованное название параметра
<.> Подсказка для ЭУ параметра
<.> Узел конструктора справочников (для параметра типа ЭУ `_Строка конструктора справочников_`)
<.> Дополнительные свойства параметра
<.> Обязательность параметра
<.> Видимость параметра на форме параметров
<.> Флаг асинхронного формирования отчёта (в задании)
<.> Описание ответа

[#GenerateReportFromApi]
== Генерация отчёта

 /api/Report/GenerateReportFromApi

.Генерация отчёта осуществляется с помощью GET запроса с параметрами:
* `reportRowId` -- обязательный параметр, ID строки отчёта в справочнике или название отчёта;
* `templateRowId` -- необязательный параметр, ID строки шаблона параметров в справочнике или название шаблона;
* `asyncGenerate` -- необязательный параметр, флаг асинхронного формирования отчёта;
* Список параметров отчёта -- необязательный параметр, параметры с множественными значениями передаются несколько раз для каждого значения.

Возвращает, в зависимости от значения asyncGenerate, имя файла отчёта для дальнейшей загрузки, либо ID задания на генерацию отчёта для отслеживания статуса генерации.

[#DownloadReport]
== Загрузка файла из файловой системы при синхронной генерации

 api/Report/DownloadReport

.Принимает GET запрос с параметрами:
* `file` -- обязательный параметр, имя файла, полученное при выполнении запроса на генерацию.

Возвращает файл с заголовками для загрузки.

[#CheckStatus]
== Отслеживание статуса задания при асинхронной генерации

 /api/Report/CheckStatus

.Принимает GET запрос с параметрами:
* `taskId` -- обязательный параметр, id задания на генерацию отчёта.

Возвращает статус задания:

* `Started` -- задание только что создано сервером и еще не взято в работу фоновым процессом,
* `In work` -- фоновый процесс взял задание в работу и начал генерацию отчёта,
* `Completed` -- задание завершено успешно и файл отчёта приложен к заданию,
* `Failed` -- задание завершилось с ошибкой либо задание завершилось, но файл отчёта не приложен к заданию. Данный статус сопровождается сообщением с текстом ошибки.

[#DownloadReportFromTask]
== Загрузка файла из задания на генерацию отчёта при асинхронной генерации

 /api/Report/DownloadReportFromTask

.Принимает GET запрос с параметрами:
* `taskId` -- обязательный параметр, ID задания на генерацию отчёта.

Возвращает файл из задания с заголовками для загрузки.


